### ISSUE TITLE
Lost chevron with "yearDropDown"

### ISSUE THREAD

**Issue by frck006** [kodaicoder/svelte-flatpickr-plus#3]
Hi

Do you know why sometime I lost chevron with "yearDropDown" ?

![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/10244725/dfc82b54-9c83-4419-9d23-88b87aa6fd94)

I put 2 dates pickers in differents position in my page and one is ok, other no.

When I inspect the page, I see differents but I don't understand why:
The second with "arrowUp/arrowDown" doesn't work.
![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/10244725/9f9834b0-c38e-401c-906b-d302391515f9)

If you have an idea... :)

PS: I use svelte carbon, perhaps their css are responsable.

Regard

**Comment by frck006** [comment]
I found.
I was using a props to pass a 'handleChange' function to my "DatePicker".
Now I use a "dispatch" to send the information back to the parent.
I don't know why but there is no more problem.

**Comment by kodaicoder** [comment]
Can you show me a code that have problem ?

**Comment by kodaicoder** [comment]
btw for a note you can using `on` directive to catching event of hook using hook name too.
e.g.
```
<input
	name="datepickerOnDirectiveDate"
	use:datePicker={dateOptions}
	on:change={changeHandler}
	on:open={openHandler}
	on:close={closeHandler}
	readonly
/>
```

or you can see a demo [here](https://svelte-flatpickr-plus.vercel.app/datepicker#eventdatepicker)

**Comment by frck006** [comment]
In fact, I've always a problem.

I want to set date programaticaly, and for this, I need to get "flatpickr" instance.
I write this code, but the first time, "fp" is undefined. :(
 
`
const getFlatpickr = (id: string): Instance | undefined => {

		if (!id) return undefined

		const fps = flatpickr(`#${id}_input`, options)

		const fp = Array.isArray(fps) ? fps[0] : fps

		return fp

	}
`

**Comment by frck006** [comment]
Ok, I think I found my problem.
It's thank to your help, with [here](https://svelte-flatpickr-plus.vercel.app/datepicker#eventdatepicker)

The problem was with calling "flatpickr" without the 3rd argument `plugins = [new yearDropdownPlugin()]`

And this example: "Date picker with flatpickr element binding" give me the solution with `bind:this={datepickerElement}`
Now, I can get the good "flatpickr": `datepickerElement._flatpickr`

Regard.
