### ISSUE TITLE
Is it possible to desactivate "YearDropDown" when "noCalendar:true" ?

### ISSUE THREAD

**Issue by frck006** [kodaicoder/svelte-flatpickr-plus#4]
Hi,

I've an exception when I just want to display "time" with my component.
(Sometime, I want to display calendar or only time and I use the same component)
If I add 
{
...
enableTime: true,
noCalendar: true
}
I've this exception:
![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/10244725/7d326c31-57f2-44c6-a3c7-6fe0c951a2f1)

I think it's because => function attachFlatpickr(node, opts, plugins = [**new yearDropdownPlugin()**]) {
If I display only time, I've not "yearDropDown".

Regards,

**Comment by kodaicoder** [comment]
this solve by PR #5
