### ISSUE TITLE
Year in dropdown doesn't change when navigating between months

### ISSUE THREAD

**Issue by oliie** [kodaicoder/svelte-flatpickr-plus#6]
The year doesn't seem to change when navigating between months. It seems like it does work on the demo page, but not in the sveltelab-example. Same goes for my project where I'm using this.

It does however set the correct year when choosing a date.

https://www.sveltelab.dev/t4zx1p7v6mcp3yj?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte

**Comment by kodaicoder** [comment]
Sorry for this issue I has notice it earlier but forget to published a release 🙏
for now you can update packages dependencies version to 1.0.4 and it will working as expected 😊

Thank you for your report on the issue.

**Comment by oliie** [comment]
Awesome! Thanks for the quick reply and fix! ❤
