### ISSUE TITLE
Cannot read properties of undefined (reading 'focus')

### ISSUE THREAD

**Issue by frck006** [kodaicoder/svelte-flatpickr-plus#7]
Hi

I think there is a problem here:
- if "altInput" is undefined or null, we call "hourElement" even I set "datePicker" instead of "TimePicker".
![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/10244725/d6fced52-01f6-4068-954d-cf7b65420d44)

Regards

**Comment by kodaicoder** [comment]
Sorry, this issue has been fixed in 1.0.8 can you try that out is it still have any further issue?

![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/110652592/6c3e8609-3987-4dee-863e-bdfbd6956952)

**Comment by frck006** [comment]
Hi, 

Not push on NPM ? (always 1.0.7)

**Comment by frck006** [comment]
It's ok, version is 1.0.9 on NPM
Thanks
