### ISSUE TITLE
Open set 'readonly' input to true.

### ISSUE THREAD

**Issue by frck006** [kodaicoder/svelte-flatpickr-plus#9]
Hi
When the popup is displayed, the "readonly" attribut is set to true.
So, we can't modify the input directly even with the "allowInput".

![image](https://github.com/kodaicoder/svelte-flatpickr-plus/assets/10244725/f9c78fce-9efa-4895-8b7e-17445fde654b)

Regards,
Franck

**Comment by kodaicoder** [comment]
Fixed in V1.0.10 👍 

Please close the issue if you not facing the issue again

Thank you for your report ❤️

**Comment by frck006** [comment]
It's ok, thanks.
